[package]
name = "path_zipper"
version = "0.1.0"
authors = ["Jan <jan@here>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.zip]
version = "0.5"
 default-features = false 
 features= ["deflate"]